/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package field;

/**
 *
 * @author Ahmed
 */
public class GameJPanel extends javax.swing.JPanel {

    private boolean gameOn = false;

    public boolean isGameOn() {
        return gameOn;
    }

    public void toggleGameOn() {
        this.gameOn = !this.gameOn;
    }

    /**
     * Creates new form FieldJPanel
     */
    public GameJPanel() {
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(20, 20, 2, 2));
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        initComponents();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
